- type: entity
  parent: BaseStructureStalkerDynamic
  id: STBaseTrashCache
  abstract: true
  name: мусор
  components:
    - type: TimedDespawn
      lifetime: 7220
    - type: Transform
      noRot: true
    - type: Storage
      maxItemSize: Huge
      grid:
        - 0,0,6,6
    - type: ContainerContainer
      containers:
        storagebase: !type:Container
    - type: UserInterface
      interfaces:
        enum.StorageUiKey.Key:
          type: StorageBoundUserInterface
    - type: Clickable
