[game]
hostname = "☢️ S.T.A.L.K.E.R. Release."
desc = "Server at S.T.A.L.K.E.R. setting.\nIn devlopment."
#map = "STWorld" # st-changes-dev-map
map_pool = "STDefaultMapPool"  # st-changes-map-pool
maxplayers = 80
soft_max_players = 60
map_rotation = false
role_timers = true
peaceful_end = false
# lobbyduration = 10
contraband_examine = false
role_whitelist = true
maxcharacterslots = 1

[rules]
time = 10.0

[whitelist]
enabled = false

[discord]
ahelp_webhook = "https://discord.com/api/webhooks/1195018829928083607/z8kIzx69ITWaUNNkcwUQHRqWtctCbgxi56RY0SnsNlH-U2WDipgSGa2YICEBUfeQbilh"

[stalker]
ban_webhook = "https://discord.com/api/webhooks/1180767180695011348/TwTaAfXkb1mYe84fgty-RKJobODmO5orWbQJOnRAbODctcLe68jYWSh44Qy2Pdz6pj64"

[shuttle]
auto_call_time = 0
emergency = false
arrivals = false
preload_grids = false
camera_rotation_locked = true

[ic]
flavor_text = true
punctuation = false

[tts]
enabled = false

[infolinks]
discord = "https://discord.gg/pu6DEPGjsN"
patreon = "https://boosty.to/stalkerss14"

[net]
sendbuffersize = 393213
receivebuffersize = 393213

[physics]
maxlinvelocity = 60.0

[hub]
advertise = false
tags = "lang:ru,lang:en,rp:high,region:eu_e"

[events]
# Annoying
enabled = false

#[worldgen]
#enabled = false
#[procgen]
#preload = false

[crewmanifest]
no_entity = false
