- type: gameMapPool
  id: DefaultMapPool
  maps:
  #stalker-changes
    - Stalker
  # - Bagel
  # - Box
  # - Cog
  # - Core
  # - Fland
  # - Marathon
  # - Meta
  # - Oasis
  # - Omega
  # - Packed
  # - Reach
  #- Train
  #stalker-changes-end
