- type: department
  id: Stalker
  color: "#9FED58"
  name: department-Stalker
  description: department-Stalker-description
  roles:
  - Stalker

# - type: department
#   id: StalkerDisabled
#   description: "department-StalkerAdvanced-description"
#   color: "#9FED58"
#   roles:
#   # - MilitaryStalker
#   #- PoliceOfficer
#   # - MayorCity
#   # - Prokuror
#   # - Magistrate
#   # - Priest
#   # - Bartender
#   # - Doctor
#   # - HeadDoctor
#   # - Police
#   # - StalkerJournalist
#   # - StalkerUN
#   # - StalkerSBU
#   # - StalkerZavet

- type: department
  id: StalkerAdvanced
  name: department-StalkerAdvanced
  description: department-StalkerAdvanced-description
  color: "#9FED58"
  roles:
  - StalkerDolg
  - StalkerHeadDolg
  - StalkerFreedom
  - StalkerHeadFreedom
  - StalkerMechanic
  - StalkerTrader
  - StalkerClown
  - StalkerClearSky
  - StalkerNeutral
  - StalkerProjectOrchestrator
  - StalkerProjectPawn
  - StalkerPoisk

- type: department
  id: StalkerBrigands
  name: department-StalkerBrigands
  description: department-StalkerBrigands-description
  color: "#111111"
  roles:
  - StalkerBandit
  - StalkerHeadBandit
  - StalkerMercenary
  - StalkerHeadMercenary
  - StalkerJaba
  - StalkerDeserter
  - StalkerRene

- type: department
  id: StalkerOfficials
  name: department-StalkerOfficials
  description: department-StalkerOfficials-description
  color: "#0000FF"
  roles:
  - Military
  - MilitaryOfficer
  - MilitaryHead
  - StalkerScientist
  - StalkerHeadScientist

- type: department
  id: StalkerReligius
  name: department-StalkerReligius
  description: department-StalkerReligius-description
  color: "#C0C0C0"
  roles:
  - StalkerPostulant
  - StalkerBishop
  - StalkerGreh
  - Seraphim
  - SeraphimHead

# - type: department
#   id: StalkerAnomalists
#   name: "department-StalkerAnomalists"
#   description: "department-StalkerAnomalists-description"
#   color: "#9FED58"
#   roles:
#   - StalkerAnomalist
#   - StalkerAnomalistGuardian
