- type: job
  id: Police
  name: полицейский
  icon: police
  description: Занимаются обеспечением безопасности и следят за соблюдением законов в предбаннике.
  playTimeTracker: JobPolice
  requirements:
    - !type:RoleTimeRequirement
      role: JobPolice
      time: 1
  startingGear: PoliceGear
  supervisors: Вы подчиняетесь старшим по званию.
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          groups:
            - PoliceOfficer
        - type: Bands
          band: Stalker
          bandIcon: police
        - type: BlockTackingHolyItems

- type: startingGear
  id: PoliceGear
  equipment:
    id: StalkerPDA
    torso: ClothingTorsoJacketPolice
    legs: ClothingLegsJeansPolice
    shoes: ClothingShoesBootsCombatFilled


