- type: entity
  parent: BaseItem
  id: BaseCraftItem
  abstract: true
  suffix: Stalker, Craft item
  components:
  - type: Craftable

- type: entity
  parent: BaseItem
  id: BaseCraftTool
  abstract: true
  components:
  - type: Craftable
  - type: Item
    size: Medium
    state: icon
    shape:
    - 0,0,1,1
  - type: Sprite
    state: icon