- type: entity
  name: базовый триггер (1-4) (20%)
  abstract: true
  id: STBaseTrigger1420
  parent: MarkerBase
  components:
    - type: ApproachTrigger
      range: 20
      minRange: 15
      useMinRange: true
      whitelist:
        components:
          - Dna
    - type: Sprite
      layers:
        - state: blue
        - sprite: Mobs/Aliens/Xenos/burrower.rsi
          state: crit
        - state: ai
    - type: SpawnOnApproach
      minAmount: 1
      maxAmount: 2
      maxOffset: 6
      minOffset: 3
      cooldown: 1800
      chance: 0.2


- type: entity
  name: базовый триггер (1-4) (100%)
  abstract: true
  id: STBaseTrigger14100
  parent: MarkerBase
  components:
    - type: ApproachTrigger
      range: 20
      minRange: 15
      useMinRange: true
      whitelist:
        components:
          - Dna
    - type: Sprite
      layers:
        - state: blue
        - sprite: Mobs/Aliens/Xenos/burrower.rsi
          state: crit
        - state: ai
    - type: SpawnOnApproach
      minAmount: 1
      maxAmount: 2
      maxOffset: 6
      minOffset: 3
      cooldown: 1800
      chance: 1

- type: entity
  name: базовый триггер (1-2) (10%)
  id: STBaseTrigger1210
  parent: MarkerBase
  abstract: true
  components:
    - type: ApproachTrigger
      range: 20
      minRange: 15
      useMinRange: true
      whitelist:
        components:
          - Dna
    - type: Sprite
      layers:
        - state: blue
        - sprite: Mobs/Aliens/Xenos/burrower.rsi
          state: crit
        - state: ai
    - type: SpawnOnApproach
      minAmount: 1
      maxAmount: 1
      maxOffset: 6
      minOffset: 3
      cooldown: 600
      chance: 0.10

- type: entity
  name: базовый триггер (1-2) (100%)
  id: STBaseTrigger12100
  abstract: true
  parent: MarkerBase
  components:
    - type: ApproachTrigger
      range: 20
      minRange: 15
      useMinRange: true
      whitelist:
        components:
          - Dna
    - type: Sprite
      layers:
        - state: blue
        - sprite: Mobs/Aliens/Xenos/burrower.rsi
          state: crit
        - state: ai
    - type: SpawnOnApproach
      minAmount: 1
      maxAmount: 1
      maxOffset: 6
      minOffset: 3
      cooldown: 600
      chance: 1

- type: entity
  name: триггер редкий моб (1) (25%)
  id: STBaseTrigger125
  abstract: true
  parent: MarkerBase
  components:
    - type: ApproachTrigger
      range: 20
      minRange: 15
      useMinRange: true
      whitelist:
        components:
          - Dna
    - type: Sprite
      layers:
        - state: blue
        - sprite: Mobs/Aliens/Xenos/burrower.rsi
          state: crit
        - state: ai
    - type: SpawnOnApproach
      minAmount: 1
      maxAmount: 1
      maxOffset: 6
      minOffset: 3
      cooldown: 1800
      chance: 0.25

- type: entity
  name: триггер босс (1) (100%)
  id: STBaseTriggerBoss
  abstract: true
  parent: MarkerBase
  components:
    - type: ApproachTrigger
      range: 20
      minRange: 15
      useMinRange: true
      whitelist:
        components:
          - Dna
    - type: Sprite
      layers:
        - state: blue
        - sprite: Mobs/Aliens/Xenos/burrower.rsi
          state: crit
        - state: ai
    - type: SpawnOnApproach
      minAmount: 1
      maxAmount: 1
      maxOffset: 6
      minOffset: 3
      cooldown: 3600
      chance: 1
